const eventData = [
     {
    id: 1,
    eventName: "Summer Music Festival",
    eventDescription: "Join us for a day of live music performances by top artists!",
    eventImage: require("./images/music_festival.jpg"),
    eventDate: "2024-07-20",
    eventLocation: "Central Park",
    eventTime: "12:00 PM - 10:00 PM",
    eventMembersRules: "Must be 18+ to attend.",
    eventCreator: "John Doe",
    eventMembers: ["Alice", "Bob", "Eve"],
    eventCost: "$50",
    isEventOpen: true,
    eventCategory: "Music",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["Music", "Festival", "Summer"]
  },
  {
    id: 2,
    eventName: "Food Truck Festival",
    eventDescription: "Savor a variety of delicious cuisines from food trucks around the city!",
    eventImage: require("./images/food_truck.jpg"),
    eventDate: "2024-08-15",
    eventLocation: "Downtown Square",
    eventTime: "11:00 AM - 8:00 PM",
    eventMembersRules: "Free entry for all ages.",
    eventCreator: "Jane Smith",
    eventMembers: ["Charlie", "David", "Grace"],
    eventCost: "Free",
    isEventOpen: true,
    eventCategory: "Food & Drink",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["Food", "Festival", "StreetFood"]
  },
  {
    id: 3,
    eventName: "Art Exhibition: Modern Masterpieces",
    eventDescription: "Explore the world of contemporary art with stunning modern artworks!",
    eventImage: require("./images/art_exhibition.jpg"),
    eventDate: "2024-09-05",
    eventLocation: "Art Gallery",
    eventTime: "10:00 AM - 6:00 PM",
    eventMembersRules: "Open to all art enthusiasts.",
    eventCreator: "Emily Brown",
    eventMembers: ["Oliver", "Sophia", "Liam"],
    eventCost: "$20",
    isEventOpen: true,
    eventCategory: "Art & Culture",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["Art", "Exhibition", "ModernArt"]
  },
  {
    id: 4,
    eventName: "Fitness Bootcamp",
    eventDescription: "Get ready to sweat it out with a high-intensity fitness bootcamp session!",
    eventImage: require("./images/fitness_bootcamp.jpg"),
    eventDate: "2024-09-10",
    eventLocation: "City Park",
    eventTime: "9:00 AM - 11:00 AM",
    eventMembersRules: "All fitness levels welcome.",
    eventCreator: "Michael Johnson",
    eventMembers: ["Emma", "Noah", "Ava"],
    eventCost: "$25",
    isEventOpen: true,
    eventCategory: "Health & Wellness",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["Fitness", "Bootcamp", "Exercise"]
  },
  {
    id: 5,
    eventName: "Tech Conference: Future Innovations",
    eventDescription: "Discover the latest trends and innovations in technology!",
    eventImage: require("./images/tech_conference.jpg"),
    eventDate: "2024-09-25",
    eventLocation: "Convention Center",
    eventTime: "9:00 AM - 5:00 PM",
    eventMembersRules: "Tech enthusiasts and professionals only.",
    eventCreator: "Andrew Wilson",
    eventMembers: ["Isabella", "William", "Mia"],
    eventCost: "$100",
    isEventOpen: true,
    eventCategory: "Technology",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["Tech", "Conference", "Innovation"]
  },
  {
    id: 6,
    eventName: "Fashion Show: Fall Collection",
    eventDescription: "Experience the latest trends in fashion at our exclusive fall collection showcase!",
    eventImage: require("./images/fashion_show.jpg"),
    eventDate: "2024-10-10",
    eventLocation: "Fashion Mall",
    eventTime: "7:00 PM - 9:00 PM",
    eventMembersRules: "Fashion enthusiasts and VIP guests only.",
    eventCreator: "Sophie Anderson",
    eventMembers: ["Lucas", "Chloe", "Ethan"],
    eventCost: "$75",
    isEventOpen: true,
    eventCategory: "Fashion",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["Fashion", "Show", "FallCollection"]
  },
  {
    id: 7,
    eventName: "Cultural Festival: Celebrating Diversity",
    eventDescription: "Celebrate diversity with cultural performances, art exhibits, and delicious international cuisines!",
    eventImage: require("./images/cultural_festival.jpg"),
    eventDate: "2024-11-01",
    eventLocation: "City Square",
    eventTime: "11:00 AM - 7:00 PM",
    eventMembersRules: "Open to all cultures and communities.",
    eventCreator: "Mohammed Ali",
    eventMembers: ["Zoe", "Daniel", "Sophie"],
    eventCost: "Free",
    isEventOpen: true,
    eventCategory: "Culture",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["CulturalFestival", "Diversity", "Celebration"]
  },
  {
    id: 8,
    eventName: "Film Festival: International Cinema",
    eventDescription: "Experience the magic of cinema with a curated selection of international films!",
    eventImage: require("./images/film_festival.jpg"),
    eventDate: "2024-11-15",
    eventLocation: "Cinema Palace",
    eventTime: "6:00 PM - 11:00 PM",
    eventMembersRules: "Film enthusiasts and movie buffs only.",
    eventCreator: "Julia Roberts",
    eventMembers: ["Henry", "Lily", "Max"],
    eventCost: "$30",
    isEventOpen: true,
    eventCategory: "Film",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["FilmFestival", "Cinema", "InternationalFilms"]
  },
  {
    id: 9,
    eventName: "Gastronomy Tour: Culinary Adventure",
    eventDescription: "Embark on a gastronomic journey exploring the city's best culinary delights!",
    eventImage: require("./images/gastronomy_tour.jpg"),
    eventDate: "2024-12-05",
    eventLocation: "Various Locations",
    eventTime: "12:00 PM - 4:00 PM",
    eventMembersRules: "Food lovers and adventurers welcome.",
    eventCreator: "Natalie Johnson",
    eventMembers: ["Adam", "Sophie", "Jacob"],
    eventCost: "$60",
    isEventOpen: true,
    eventCategory: "Food & Drink",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["Gastronomy", "Tour", "CulinaryAdventure"]
  },
  {
    id: 10,
    eventName: "Comedy Night: Stand-up Special",
    eventDescription: "Get ready for a night of laughter with top comedians performing live stand-up comedy!",
    eventImage: require("./images/comedy_night.jpg"),
    eventDate: "2025-01-10",
    eventLocation: "Comedy Club",
    eventTime: "8:00 PM - 10:00 PM",
    eventMembersRules: "Adults only (18+).",
    eventCreator: "Kevin Hart",
    eventMembers: ["Sophia", "Jack", "Ella"],
    eventCost: "$20",
    isEventOpen: true,
    eventCategory: "Entertainment",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["ComedyNight", "StandUpComedy", "Laughs"]
  },
  {
    id: 11,
    eventName: "Tech Workshop: Web Development",
    eventDescription: "Learn the latest web development technologies and frameworks in this hands-on workshop!",
    eventImage: require("./images/tech_workshop.jpg"),
    eventDate: "2025-02-15",
    eventLocation: "Tech Hub",
    eventTime: "10:00 AM - 4:00 PM",
    eventMembersRules: "Tech enthusiasts and beginners welcome.",
    eventCreator: "Sarah Williams",
    eventMembers: ["Ethan", "Emily", "Liam"],
    eventCost: "$50",
    isEventOpen: true,
    eventCategory: "Technology",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["Tech", "Workshop", "WebDevelopment"]
  },
  {
    id: 12,
    eventName: "Music Concert: Jazz Night",
    eventDescription: "Experience the soulful melodies of jazz with live performances by renowned jazz musicians!",
    eventImage: require("./images/jazz_concert.jpg"),
    eventDate: "2025-03-20",
    eventLocation: "Jazz Club",
    eventTime: "7:00 PM - 11:00 PM",
    eventMembersRules: "Music lovers of all ages.",
    eventCreator: "Miles Davis",
    eventMembers: ["Olivia", "James", "Ava"],
    eventCost: "$35",
    isEventOpen: true,
    eventCategory: "Music",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["Music", "Concert", "Jazz"]
  },
  {
    id: 13,
    eventName: "Fashion Week: Spring Collection",
    eventDescription: "Witness the latest trends in fashion at our exclusive spring collection showcase!",
    eventImage: require("./images/fashion_week.jpg"),
    eventDate: "2025-04-10",
    eventLocation: "Fashion Mall",
    eventTime: "6:00 PM - 10:00 PM",
    eventMembersRules: "Fashion enthusiasts and VIP guests only.",
    eventCreator: "Victoria Beckham",
    eventMembers: ["Alexander", "Luna", "Liam"],
    eventCost: "$100",
    isEventOpen: true,
    eventCategory: "Fashion",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["FashionWeek", "SpringCollection", "Runway"]
  },
  {
    id: 14,
    eventName: "Food Festival: International Flavors",
    eventDescription: "Indulge in a culinary journey exploring flavors from around the world at our international food festival!",
    eventImage: require("./images/food_festival.jpg"),
    eventDate: "2025-05-15",
    eventLocation: "Food Park",
    eventTime: "11:00 AM - 9:00 PM",
    eventMembersRules: "Food lovers of all ages.",
    eventCreator: "Gordon Ramsay",
    eventMembers: ["Emma", "Jacob", "Sophia"],
    eventCost: "Free entry, food prices vary.",
    isEventOpen: true,
    eventCategory: "Food & Drink",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["FoodFestival", "InternationalFlavors", "Cuisine"]
  },
  {
    id: 15,
    eventName: "Film Premiere: Blockbuster Movie",
    eventDescription: "Be the first to watch the premiere of the highly-anticipated blockbuster movie!",
    eventImage: require("./images/film_premiere.jpg"),
    eventDate: "2025-06-20",
    eventLocation: "Cinema Palace",
    eventTime: "7:00 PM - 10:00 PM",
    eventMembersRules: "Movie enthusiasts and VIP guests only.",
    eventCreator: "Steven Spielberg",
    eventMembers: ["Sophie", "Benjamin", "Charlotte"],
    eventCost: "$50",
    isEventOpen: true,
    eventCategory: "Film",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["FilmPremiere", "Blockbuster", "MovieNight"]
  },
  {
    id: 16,
    eventName: "Art Workshop: Painting Masterclass",
    eventDescription: "Unleash your creativity in this hands-on painting masterclass with expert artists!",
    eventImage: require("./images/art_workshop.jpg"),
    eventDate: "2025-07-15",
    eventLocation: "Art Studio",
    eventTime: "10:00 AM - 2:00 PM",
    eventMembersRules: "Art enthusiasts of all levels.",
    eventCreator: "Pablo Picasso",
    eventMembers: ["Liam", "Ella", "Jacob"],
    eventCost: "$40",
    isEventOpen: true,
    eventCategory: "Art & Culture",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["Art", "Workshop", "Painting"]
  },
  {
    id: 17,
    eventName: "Tech Summit: Future Trends",
    eventDescription: "Explore the future trends and innovations in technology at our tech summit!",
    eventImage: require("./images/tech_summit.jpg"),
    eventDate: "2025-08-10",
    eventLocation: "Tech Hub",
    eventTime: "9:00 AM - 6:00 PM",
    eventMembersRules: "Tech professionals and enthusiasts.",
    eventCreator: "Elon Musk",
    eventMembers: ["Ava", "Ethan", "Sophie"],
    eventCost: "$150",
    isEventOpen: true,
    eventCategory: "Technology",
    isEventPopular: true,
    isUpComingEvent: true,
    eventHashTags: ["Tech", "Summit", "FutureTrends"]
  },
]