  const subscriptionData = [
    {
      id: 1,
      planName: "Splinx-Planet monthly subscription plan: Platinum 5.99 usd/month",
      type: "monthly",
      interval: "monthly",
      period: "1 month",
      price: "$5.99/month",
      amount: 5.99,
      title: "Platinum Basic",
      description: "7 days trial then $5.99/month.",
      isRecurring: true,
    },
    // {
    //   id: 2,
    //   planName: "Splinx-Planet six monthly subscription plan: Platinum 53.94 usd/6-month",
    //   type: "six-months",
    //   interval: "every 6 months",
    //   period: "6 months",
    //   price: "$53.94/6 months",
    //   amount: 53.94,
    //   description: "3 days trial then $53.94/6 months.",
    //   isRecurring: true,
    // },
    {
      id: 3,
      planName: "Splinx-Planet monthly subscription plan: Platinum 10.99 usd/year",
      type: "monthly",
      interval: "monthly",
      period: "1 month",
      price: "$10.99/month",
      amount: 10.99,
      title: "Platinum Pro",
      description: "7 days trial then $10.99/monthly.",
      isRecurring: true,
    },
    {
      id: 4,
      planName: "Splinx-Planet monthly subscription plan: Ballers upgrade 14.99 usd/month",
      type: "monthly",
      period: "1 month",
      price: "$14.99",
      amount: 14.99,
      title: "Ballers",
      description: "Upgrade to ballers for $14.99/monthly",
      isRecurring: true,
    },
  ];

  export default subscriptionData;