  const subscriptionData = [
    {
      id: 1,
      planName: "Splinx-Planet monthly subscription plan: Platinum 9.99 usd/month",
      type: "monthly",
      interval: "monthly",
      period: "1 month",
      price: "$9.99/month",
      amount: 9.99,
      description: "3 days trial then $9.99/month.",
      isRecurring: true,
    },
    {
      id: 2,
      planName: "Splinx-Planet six monthly subscription plan: Platinum 53.94 usd/6-month",
      type: "six-months",
      interval: "every 6 months",
      period: "6 months",
      price: "$53.94/6 months",
      amount: 53.94,
      description: "3 days trial then $53.94/6 months.",
      isRecurring: true,
    },
    {
      id: 3,
      planName: "Splinx-Planet yearly subscription plan: Platinum 95.88 usd/year",
      type: "one-year",
      interval: "yearly",
      period: "12 months",
      price: "$95.88/year",
      amount: 95.88,
      description: "3 days trial then $95.88/1 year.",
      isRecurring: true,
    },
    {
      id: 4,
      planName: "Splinx-Planet yearly subscription plan: Ballers upgrade 29.99 usd/month",
      type: "yearly",
      period: "12 months",
      price: "$29.99",
      amount: 29.99,
      description: "Upgrade to ballers for $29.99/m",
      isRecurring: true,
    },
  ];

  export default subscriptionData;